/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SudoRouteImport } from './routes/sudo'
import { Route as PoweredOffRouteImport } from './routes/powered-off'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedSyllabusRouteImport } from './routes/_authenticated/syllabus'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedProjectsRouteImport } from './routes/_authenticated/projects'
import { Route as AuthenticatedPlannerRouteImport } from './routes/_authenticated/planner'
import { Route as AuthenticatedNovelRouteImport } from './routes/_authenticated/novel'
import { Route as AuthenticatedInspirationRouteImport } from './routes/_authenticated/inspiration'
import { Route as AuthenticatedHabitsRouteImport } from './routes/_authenticated/habits'
import { Route as AuthenticatedCodeRouteImport } from './routes/_authenticated/code'
import { Route as AuthenticatedAiRouteImport } from './routes/_authenticated/ai'

const SudoRoute = SudoRouteImport.update({
  id: '/sudo',
  path: '/sudo',
  getParentRoute: () => rootRouteImport,
} as any)
const PoweredOffRoute = PoweredOffRouteImport.update({
  id: '/powered-off',
  path: '/powered-off',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSyllabusRoute = AuthenticatedSyllabusRouteImport.update({
  id: '/syllabus',
  path: '/syllabus',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProjectsRoute = AuthenticatedProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPlannerRoute = AuthenticatedPlannerRouteImport.update({
  id: '/planner',
  path: '/planner',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedNovelRoute = AuthenticatedNovelRouteImport.update({
  id: '/novel',
  path: '/novel',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedInspirationRoute =
  AuthenticatedInspirationRouteImport.update({
    id: '/inspiration',
    path: '/inspiration',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedHabitsRoute = AuthenticatedHabitsRouteImport.update({
  id: '/habits',
  path: '/habits',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCodeRoute = AuthenticatedCodeRouteImport.update({
  id: '/code',
  path: '/code',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAiRoute = AuthenticatedAiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => AuthenticatedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/login': typeof LoginRoute
  '/powered-off': typeof PoweredOffRoute
  '/sudo': typeof SudoRoute
  '/ai': typeof AuthenticatedAiRoute
  '/code': typeof AuthenticatedCodeRoute
  '/habits': typeof AuthenticatedHabitsRoute
  '/inspiration': typeof AuthenticatedInspirationRoute
  '/novel': typeof AuthenticatedNovelRoute
  '/planner': typeof AuthenticatedPlannerRoute
  '/projects': typeof AuthenticatedProjectsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/syllabus': typeof AuthenticatedSyllabusRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/powered-off': typeof PoweredOffRoute
  '/sudo': typeof SudoRoute
  '/ai': typeof AuthenticatedAiRoute
  '/code': typeof AuthenticatedCodeRoute
  '/habits': typeof AuthenticatedHabitsRoute
  '/inspiration': typeof AuthenticatedInspirationRoute
  '/novel': typeof AuthenticatedNovelRoute
  '/planner': typeof AuthenticatedPlannerRoute
  '/projects': typeof AuthenticatedProjectsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/syllabus': typeof AuthenticatedSyllabusRoute
  '/': typeof AuthenticatedIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/powered-off': typeof PoweredOffRoute
  '/sudo': typeof SudoRoute
  '/_authenticated/ai': typeof AuthenticatedAiRoute
  '/_authenticated/code': typeof AuthenticatedCodeRoute
  '/_authenticated/habits': typeof AuthenticatedHabitsRoute
  '/_authenticated/inspiration': typeof AuthenticatedInspirationRoute
  '/_authenticated/novel': typeof AuthenticatedNovelRoute
  '/_authenticated/planner': typeof AuthenticatedPlannerRoute
  '/_authenticated/projects': typeof AuthenticatedProjectsRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/syllabus': typeof AuthenticatedSyllabusRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/powered-off'
    | '/sudo'
    | '/ai'
    | '/code'
    | '/habits'
    | '/inspiration'
    | '/novel'
    | '/planner'
    | '/projects'
    | '/settings'
    | '/syllabus'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/powered-off'
    | '/sudo'
    | '/ai'
    | '/code'
    | '/habits'
    | '/inspiration'
    | '/novel'
    | '/planner'
    | '/projects'
    | '/settings'
    | '/syllabus'
    | '/'
  id:
    | '__root__'
    | '/_authenticated'
    | '/login'
    | '/powered-off'
    | '/sudo'
    | '/_authenticated/ai'
    | '/_authenticated/code'
    | '/_authenticated/habits'
    | '/_authenticated/inspiration'
    | '/_authenticated/novel'
    | '/_authenticated/planner'
    | '/_authenticated/projects'
    | '/_authenticated/settings'
    | '/_authenticated/syllabus'
    | '/_authenticated/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  PoweredOffRoute: typeof PoweredOffRoute
  SudoRoute: typeof SudoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sudo': {
      id: '/sudo'
      path: '/sudo'
      fullPath: '/sudo'
      preLoaderRoute: typeof SudoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/powered-off': {
      id: '/powered-off'
      path: '/powered-off'
      fullPath: '/powered-off'
      preLoaderRoute: typeof PoweredOffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/syllabus': {
      id: '/_authenticated/syllabus'
      path: '/syllabus'
      fullPath: '/syllabus'
      preLoaderRoute: typeof AuthenticatedSyllabusRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/projects': {
      id: '/_authenticated/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof AuthenticatedProjectsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/planner': {
      id: '/_authenticated/planner'
      path: '/planner'
      fullPath: '/planner'
      preLoaderRoute: typeof AuthenticatedPlannerRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/novel': {
      id: '/_authenticated/novel'
      path: '/novel'
      fullPath: '/novel'
      preLoaderRoute: typeof AuthenticatedNovelRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/inspiration': {
      id: '/_authenticated/inspiration'
      path: '/inspiration'
      fullPath: '/inspiration'
      preLoaderRoute: typeof AuthenticatedInspirationRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/habits': {
      id: '/_authenticated/habits'
      path: '/habits'
      fullPath: '/habits'
      preLoaderRoute: typeof AuthenticatedHabitsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/code': {
      id: '/_authenticated/code'
      path: '/code'
      fullPath: '/code'
      preLoaderRoute: typeof AuthenticatedCodeRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/ai': {
      id: '/_authenticated/ai'
      path: '/ai'
      fullPath: '/ai'
      preLoaderRoute: typeof AuthenticatedAiRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAiRoute: typeof AuthenticatedAiRoute
  AuthenticatedCodeRoute: typeof AuthenticatedCodeRoute
  AuthenticatedHabitsRoute: typeof AuthenticatedHabitsRoute
  AuthenticatedInspirationRoute: typeof AuthenticatedInspirationRoute
  AuthenticatedNovelRoute: typeof AuthenticatedNovelRoute
  AuthenticatedPlannerRoute: typeof AuthenticatedPlannerRoute
  AuthenticatedProjectsRoute: typeof AuthenticatedProjectsRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedSyllabusRoute: typeof AuthenticatedSyllabusRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAiRoute: AuthenticatedAiRoute,
  AuthenticatedCodeRoute: AuthenticatedCodeRoute,
  AuthenticatedHabitsRoute: AuthenticatedHabitsRoute,
  AuthenticatedInspirationRoute: AuthenticatedInspirationRoute,
  AuthenticatedNovelRoute: AuthenticatedNovelRoute,
  AuthenticatedPlannerRoute: AuthenticatedPlannerRoute,
  AuthenticatedProjectsRoute: AuthenticatedProjectsRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedSyllabusRoute: AuthenticatedSyllabusRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  PoweredOffRoute: PoweredOffRoute,
  SudoRoute: SudoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
