import { useEffect, useState } from "react";
import { RetroWindow } from "@/components/RetroWindow";
import { Quote, RefreshCw } from "lucide-react";

const quotes = [
  { t: "Stay hungry. Stay foolish.", a: "Steve Jobs" },
  { t: "Make it work, make it right, make it fast.", a: "Kent Beck" },
  { t: "The future depends on what you do today.", a: "Gandhi" },
  { t: "Simplicity is the ultimate sophistication.", a: "da Vinci" },
  { t: "First, solve the problem. Then, write the code.", a: "John Johnson" },
  { t: "Creativity is intelligence having fun.", a: "Einstein" },
  { t: "Discipline will take you places motivation never could.", a: "Unknown" },
  { t: "Your comeback starts the moment you stop making excuses.", a: "Unknown" },
  { t: "Winter arc begins where comfort ends.", a: "Unknown" },
  { t: "Small progress every day builds unstoppable momentum.", a: "Unknown" },
  { t: "The pain you feel today becomes the strength you carry tomorrow.", a: "Unknown" },
  { t: "You either suffer the pain of discipline or the pain of regret.", a: "Jim Rohn" },
  { t: "Nobody cares. Work harder.", a: "Unknown" },
  { t: "Success is built in silence.", a: "Unknown" },
  { t: "Your future self is watching your decisions right now.", a: "Unknown" },
  { t: "The comeback is always stronger than the setback.", a: "Unknown" },
  { t: "Train your mind to stay calm in chaos.", a: "Unknown" },
  { t: "Great things never come from comfort zones.", a: "Unknown" },
  { t: "The hardest battles create the strongest warriors.", a: "Unknown" },
  { t: "Dreams demand discipline.", a: "Unknown" },
  { t: "When you feel like quitting, remember why you started.", a: "Unknown" },
  { t: "Pressure creates diamonds.", a: "Unknown" },
  { t: "You were not born to stay average.", a: "Unknown" },
  { t: "Late nights. Early mornings. No excuses.", a: "Unknown" },
  { t: "Your habits decide your future.", a: "Unknown" },
  { t: "Focus on progress, not applause.", a: "Unknown" },
  { t: "The strongest glow comes after the darkest nights.", a: "Unknown" },
  { t: "Winter arc is about becoming unrecognizable.", a: "Unknown" },
  { t: "One year of focus can change your entire life.", a: "Unknown" },
  { t: "Comfort is expensive.", a: "Unknown" },
  { t: "Discipline is self-respect in action.", a: "Unknown" },
  { t: "Silence your doubts with results.", a: "Unknown" },
  { t: "Every champion was once inconsistent.", a: "Unknown" },
  { t: "Stay patient. Your time is coming.", a: "Unknown" },
  { t: "The grind looks lonely before it looks legendary.", a: "Unknown" },
  { t: "Become addicted to improving yourself.", a: "Unknown" },
  { t: "A focused mind is a dangerous weapon.", a: "Unknown" },
  { t: "Success loves consistency.", a: "Unknown" },
  { t: "Excuses kill more dreams than failure ever will.", a: "Unknown" },
  { t: "Wake up with purpose.", a: "Unknown" },
  { t: "You can restart at any moment.", a: "Unknown" },
  { t: "Nobody is coming to save you.", a: "Unknown" },
  { t: "The version of you next year depends on your actions today.", a: "Unknown" },
  { t: "Hard times introduce strong people.", a: "Unknown" },
  { t: "Discipline turns vision into reality.", a: "Unknown" },
  { t: "Your competition is your old self.", a: "Unknown" },
  { t: "Stay focused. Stay dangerous.", a: "Unknown" },
  { t: "Every rep counts.", a: "Unknown" },
  { t: "The grind never lies.", a: "Unknown" },
  { t: "Your mindset shapes your reality.", a: "Unknown" },
  { t: "Be obsessed with your goals.", a: "Unknown" },
  { t: "Fall seven times. Rise eight.", a: "Japanese Proverb" },
  { t: "Confidence is built through preparation.", a: "Unknown" },
  { t: "Winter arc means sacrificing comfort for growth.", a: "Unknown" },
  { t: "Push yourself because nobody else will.", a: "Unknown" },
  { t: "The work you avoid is the work you need most.", a: "Unknown" },
  { t: "Stay hungry. Stay relentless.", a: "Unknown" },
  { t: "Fear disappears when preparation increases.", a: "Unknown" },
  { t: "A winner is just a loser who kept going.", a: "Unknown" },
  { t: "Every day is a new chance to level up.", a: "Unknown" },
  { t: "Your discipline should be louder than your excuses.", a: "Unknown" },
  { t: "Do it tired. Do it uninspired. Just do it.", a: "Unknown" },
  { t: "The strongest people are built in isolation.", a: "Unknown" },
  { t: "Consistency beats intensity.", a: "Unknown" },
  { t: "Your comeback story starts now.", a: "Unknown" },
  { t: "Master yourself and everything changes.", a: "Unknown" },
  { t: "The future rewards those who stay consistent.", a: "Unknown" },
  { t: "Stay locked in.", a: "Unknown" },
  { t: "The gym teaches what comfort never can.", a: "Unknown" },
  { t: "No distractions. No excuses. Just results.", a: "Unknown" },
  { t: "You are capable of far more than you think.", a: "Unknown" },
  { t: "Discipline creates freedom.", a: "Jocko Willink" },
  { t: "A cold morning builds a warm future.", a: "Unknown" },
  { t: "Outwork your old excuses.", a: "Unknown" },
  { t: "Stay patient with the process.", a: "Unknown" },
  { t: "Mental toughness is earned daily.", a: "Unknown" },
  { t: "The best revenge is self-improvement.", a: "Unknown" },
  { t: "Strength grows in struggle.", a: "Unknown" },
  { t: "You become what you repeat.", a: "Unknown" },
  { t: "Discomfort is a sign of growth.", a: "Unknown" },
  { t: "One disciplined year can change everything.", a: "Unknown" },
  { t: "Your habits are your identity.", a: "Unknown" },
  { t: "Winter arc is built one hard day at a time.", a: "Unknown" },
  { t: "The grind is temporary. Regret lasts forever.", a: "Unknown" },
  { t: "Success begins with self-control.", a: "Unknown" },
  { t: "Stay consistent even when nobody notices.", a: "Unknown" },
  { t: "Pain is temporary. Pride is forever.", a: "Unknown" },
  { t: "Greatness requires sacrifice.", a: "Unknown" },
  { t: "Your only limit is your discipline.", a: "Unknown" },
  { t: "Keep showing up.", a: "Unknown" },
  { t: "Focus is a superpower.", a: "Unknown" },
  { t: "Build yourself in silence.", a: "Unknown" },
  { t: "Every setback carries a lesson.", a: "Unknown" },
  { t: "The strongest version of you is waiting.", a: "Unknown" },
  { t: "Winners embrace hard days.", a: "Unknown" },
  { t: "Pressure reveals character.", a: "Unknown" },
  { t: "Your dreams deserve your effort.", a: "Unknown" },
  { t: "Hard work compounds.", a: "Unknown" },
  { t: "A disciplined life is a powerful life.", a: "Unknown" },
  { t: "Become impossible to ignore.", a: "Unknown" },
  { t: "Keep grinding until your idols become your rivals.", a: "Unknown" },
  { t: "Success starts with showing up.", a: "Unknown" },
  { t: "This is your season of transformation.", a: "Unknown" },
  { t: "The comeback always shocks the doubters.", a: "Unknown" },
  { t: "Your excuses are stealing your potential.", a: "Unknown" },
  { t: "Cold mornings create disciplined minds.", a: "Unknown" },
  { t: "The comeback begins when the excuses end.", a: "Unknown" },
  { t: "Every late night adds another brick to success.", a: "Unknown" },
  { t: "Winter arc is built in silence.", a: "Unknown" },
  { t: "You either evolve or repeat the same year forever.", a: "Unknown" },
  { t: "Nobody can stop a person obsessed with growth.", a: "Unknown" },
  { t: "The grind becomes addictive once results appear.", a: "Unknown" },
  { t: "Pain fades. Discipline remains.", a: "Unknown" },
  { t: "Your future self is begging you to stay consistent.", a: "Unknown" },
  { t: "Discipline is choosing what matters most.", a: "Unknown" },
  { t: "A focused mind creates unstoppable energy.", a: "Unknown" },
  { t: "Hard work exposes hidden strength.", a: "Unknown" },
  { t: "The strongest comeback starts from rock bottom.", a: "Unknown" },
  { t: "Success is hidden inside repetition.", a: "Unknown" },
  { t: "The process transforms more than the outcome.", a: "Unknown" },
  { t: "Winter arc means sacrificing comfort daily.", a: "Unknown" },
  { t: "Train your mind to stay calm under pressure.", a: "Unknown" },
  { t: "Every disciplined action compounds over time.", a: "Unknown" },
  { t: "You were built to do hard things.", a: "Unknown" },
  { t: "The strongest version of you needs patience.", a: "Unknown" },
  { t: "Growth starts where comfort dies.", a: "Unknown" },
  { t: "Your habits decide your destiny.", a: "Unknown" },
  { t: "Silence your doubts with progress.", a: "Unknown" },
  { t: "Nobody regrets becoming stronger.", a: "Unknown" },
  { t: "The grind teaches lessons comfort never could.", a: "Unknown" },
  { t: "Discipline is your unfair advantage.", a: "Unknown" },
  { t: "Small improvements create massive changes.", a: "Unknown" },
  { t: "Your comeback is earned through consistency.", a: "Unknown" },
  { t: "Every challenge sharpens your mindset.", a: "Unknown" },
  { t: "Success requires uncomfortable sacrifices.", a: "Unknown" },
  { t: "A disciplined person fears nothing.", a: "Unknown" },
  { t: "Stay focused even when nobody notices.", a: "Unknown" },
  { t: "Winter arc is about becoming unstoppable.", a: "Unknown" },
  { t: "You grow every time you refuse to quit.", a: "Unknown" },
  { t: "Pressure creates resilient minds.", a: "Unknown" },
  { t: "Excuses destroy more dreams than failure.", a: "Unknown" },
  { t: "The grind rewards patience eventually.", a: "Unknown" },
  { t: "Your future depends on your standards.", a: "Unknown" },
  { t: "Hard times reveal true character.", a: "Unknown" },
  { t: "The strongest minds embrace discomfort.", a: "Unknown" },
  { t: "Nobody can outwork consistency.", a: "Unknown" },
  { t: "Discipline turns ordinary into extraordinary.", a: "Unknown" },
  { t: "Every setback contains hidden growth.", a: "Unknown" },
  { t: "Winter arc starts with accountability.", a: "Unknown" },
  { t: "Focus on progress instead of perfection.", a: "Unknown" },
  { t: "Your grind will eventually introduce you to success.", a: "Unknown" },
  { t: "Discomfort is proof you're evolving.", a: "Unknown" },
  { t: "The gym builds mental strength too.", a: "Unknown" },
  { t: "Stay committed when motivation disappears.", a: "Unknown" },
  { t: "Strong habits create strong futures.", a: "Unknown" },
  { t: "Every disciplined morning changes your life.", a: "Unknown" },
  { t: "Your comeback starts with one decision.", a: "Unknown" },
  { t: "The strongest people master boring routines.", a: "Unknown" },
  { t: "Success grows quietly behind discipline.", a: "Unknown" },
  { t: "A better future demands present sacrifice.", a: "Unknown" },
  { t: "The grind never lies about effort.", a: "Unknown" },
  { t: "Winter arc is self-respect in action.", a: "Unknown" },
  { t: "You become what you repeatedly do.", a: "Unknown" },
  { t: "Discipline survives when motivation fails.", a: "Unknown" },
  { t: "Pressure creates diamonds and leaders.", a: "Unknown" },
  { t: "The strongest transformations happen privately.", a: "Unknown" },
  { t: "Success starts before anyone notices.", a: "Unknown" },
  { t: "Every difficult day strengthens your mindset.", a: "Unknown" },
  { t: "Your goals deserve consistency.", a: "Unknown" },
  { t: "Nobody can replace hard work.", a: "Unknown" },
  { t: "Winter arc rewards relentless effort.", a: "Unknown" },
  { t: "The process creates confidence.", a: "Unknown" },
  { t: "Stay disciplined through every season.", a: "Unknown" },
  { t: "You either sacrifice now or regret later.", a: "Unknown" },
  { t: "A strong routine creates a strong life.", a: "Unknown" },
  { t: "Every rep builds discipline.", a: "Unknown" },
  { t: "Your standards shape your future.", a: "Unknown" },
  { t: "The grind reveals your priorities.", a: "Unknown" },
  { t: "Success rewards consistency quietly.", a: "Unknown" },
  { t: "The comeback always shocks doubters.", a: "Unknown" },
  { t: "Discipline creates unstoppable momentum.", a: "Unknown" },
  { t: "Winter arc is built through lonely mornings.", a: "Unknown" },
  { t: "Every sacrifice adds another layer of strength.", a: "Unknown" },
  { t: "A focused life creates powerful outcomes.", a: "Unknown" },
  { t: "Hard work eventually becomes visible.", a: "Unknown" },
  { t: "Nobody builds greatness overnight.", a: "Unknown" },
  { t: "The strongest glow follows dark seasons.", a: "Unknown" },
  { t: "Consistency separates winners from dreamers.", a: "Unknown" },
  { t: "Discipline is confidence earned daily.", a: "Unknown" },
  { t: "The grind changes your identity.", a: "Unknown" },
  { t: "Your comeback begins in silence.", a: "Unknown" },
  { t: "Winter arc means becoming disciplined daily.", a: "Unknown" },
  { t: "Pressure reveals weak habits quickly.", a: "Unknown" },
  { t: "The strongest people keep showing up.", a: "Unknown" },
  { t: "Focus creates opportunities distractions destroy.", a: "Unknown" },
  { t: "Success belongs to disciplined minds.", a: "Unknown" },
  { t: "Every challenge develops resilience.", a: "Unknown" },
  { t: "The process matters more than applause.", a: "Unknown" },
  { t: "Nobody notices preparation until victory arrives.", a: "Unknown" },
  { t: "Discomfort creates transformation.", a: "Unknown" },
  { t: "Your effort today builds tomorrow.", a: "Unknown" },
  { t: "Winter arc is earned through sacrifice.", a: "Unknown" },
  { t: "Stay patient with your transformation.", a: "Unknown" },
  { t: "The grind rewards disciplined people.", a: "Unknown" },
  { t: "Every disciplined action builds momentum.", a: "Unknown" },
];

export function QuoteWidget() {
  const [i, setI] = useState(0);
  useEffect(() => { setI(Math.floor(Math.random() * quotes.length)); }, []);
  const q = quotes[i];
  return (
    <RetroWindow
      title="muse.txt"
      icon={<Quote className="h-3.5 w-3.5" />}
      actions={
        <button onClick={() => setI((p) => (p + 1) % quotes.length)} aria-label="Next">
          <RefreshCw className="h-3.5 w-3.5" />
        </button>
      }
    >
      <blockquote className="font-display text-xl sm:text-2xl leading-snug">"{q.t}"</blockquote>
      <div className="mt-2 text-xs font-mono opacity-70">— {q.a}</div>
    </RetroWindow>
  );
}
